[build]
  base = "ecommerce"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://146.190.75.136:4242/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200